### PR TITLE
Setup go modules

### PR DESCRIPTION
**Pull request by anthonyraymond**
Add go modules support.

Recommended actions before merging:
 - Remove the v2 branch (as it can conflict with the *go module* resolution)
 - Create a branch named v1 (with head being the last v1 tag)

### CODE REVIEW

**Comment by worg** [comment]
Hey @anthonyraymond thanks for the PR, unfortunately I think the cat got out the bag for V2. I think the best approach would be to mark the module support as V3, at the end of the day it's a breaking change, can you please update the PR to use V3 instead? thanks!

**Comment by anthonyraymond** [comment]
Hi @worg 

That makes sense.

The two PR i have sent so far are a preparation for a bigger one that allow stomp over WebSocket and make the library extenssibles to allow stomp over whatever user want.

Instead of merging this one first what we can do is :
- i send the Websocket PR
- You review it
- If it's fine with you, we merge the gomodule (labeled as v3)
- we merge the websocket one
- You tag the new commit with v3.0.0

Because increasing major version seems a bit weird to me, but if you prefer i can update this PR to be v3 and websocket v4.

What do you think about that?

**Comment by worg** [comment]
Hey @anthonyraymond , go-stomp already supports any transport (WebSockets, TLS, anything that returns an io.ReadWriteCloser in fact), the [Connect](https://pkg.go.dev/github.com/go-stomp/stomp@v2.1.0+incompatible#Connect) should allow you to do that, so the Websocket PR might not be the best choice, probably adding better documentation on this might help, I'll set up some time to add more docs on the use of Connect.
Are you ok if we work the V3 PR against a new branch?

**Comment by worg** [comment]
I'd take the approach shown here: https://blog.golang.org/v2-go-modules
Which means copying the current version into a new `v3` directory and do all the work there.

**Comment by worg** [comment]
@anthonyraymond Are you ok with me starting the changes outlined in that blog post for v3?

**Comment by anthonyraymond** [comment]
Hello @worg i've seen that blog post as well, this is the *official* way to migrate to module while keeping backward compatibility.

But i've always been a bit skeptical about this for multiple reasons:
- import nightmare for whose who are developing the library: frame.Frame can be imported from `github.com/go-stomp/stomp`, `github.com/go-stomp/stomp/v2` or `github.com/go-stomp/stomp/v3`, ...
- people will have to know that origin/master code is an old and unmaintained code base and instead should look at the v2, v3, v4 folders

But the other way around is to do what we discussed earlier and this will be a breaking change for those who aren't using go modules yet.
So i see advantage on both sides but what you prefer is your choice :), i any case i can sent you a PR for the solution you prefer

**Comment by worg** [comment]
I'd like to also know what's @jjeffery opinion on this

**Comment by worg** [comment]
@anthonyraymond sorry for the delay on this.
Closed in favor of #94

**Pull request closed without merging**
