### PR TITLE
Make it possible to set logger

### PR DESCRIPTION
**Pull request by codemedic**
Allowing to set the logger makes it possible for those using go-stomp to customise logging.

### CODE REVIEW

**Comment by worg** [comment]
Hey! Thanks for the PR, given most of the logging happens on the connection I'd like to avoid the global `logger` variable and the `SetLogger` method, how about adding the logger to the `Connection`, and add a new `ConnOpt` to set the logger on creation so each conn has its own logger, with less margin to error with multiple callers/concurrent calls of `SetLogger`?

**Comment by codemedic** [comment]
@worg Thanks for taking a look at my changes.
Using `ConnOpt` makes sense; should have done that first time around.

**Comment by codemedic** [comment]
One more change to fix a bug (see commit message for 1c502e8).

**Comment by codemedic** [comment]
This evening, I have published a levelled-logging library that implements the `Logger` interface.
See https://github.com/codemedic/go-log

**Comment by worg** [comment]
LGTM

**Pull request merged**
